// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrainRegistry.Infrastructure.Persistence;

#nullable disable

namespace TrainRegistry.Infrastructure.Migrations
{
    [DbContext(typeof(TrainDbContext))]
    [Migration("20260626132505_AddValueObjects")]
    partial class AddValueObjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrainRegistry.Domain.Entities.Train", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("TrainRegistry.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TrainRegistry.Domain.Entities.Train", b =>
                {
                    b.OwnsOne("TrainRegistry.Domain.ValueObjects.TrainLength", "Length", b1 =>
                        {
                            b1.Property<Guid>("TrainId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("Length");

                            b1.HasKey("TrainId");

                            b1.ToTable("Trains");

                            b1.WithOwner()
                                .HasForeignKey("TrainId");
                        });

                    b.OwnsOne("TrainRegistry.Domain.ValueObjects.TrainSpeed", "Speed", b1 =>
                        {
                            b1.Property<Guid>("TrainId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("Speed");

                            b1.HasKey("TrainId");

                            b1.ToTable("Trains");

                            b1.WithOwner()
                                .HasForeignKey("TrainId");
                        });

                    b.OwnsOne("TrainRegistry.Domain.ValueObjects.TrainStatus", "TrainStatus", b1 =>
                        {
                            b1.Property<Guid>("TrainId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("TrainStatus");

                            b1.HasKey("TrainId");

                            b1.ToTable("Trains");

                            b1.WithOwner()
                                .HasForeignKey("TrainId");
                        });

                    b.Navigation("Length")
                        .IsRequired();

                    b.Navigation("Speed")
                        .IsRequired();

                    b.Navigation("TrainStatus")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
